version: "3.8"

services:
  app:
    image: ghcr.io/georgeazevedo2023/whatspro:latest
    build: .
    networks:
      - wsmart
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whatspro.rule=Host(`crm.wsmart.com.br`)"
        - "traefik.http.routers.whatspro.entrypoints=websecure"
        - "traefik.http.routers.whatspro.tls.certresolver=letsencrypt"
        - "traefik.http.services.whatspro.loadbalancer.server.port=80"

networks:
  wsmart:
    external: true
