import { useState, useEffect, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import {
  User, ShoppingCart, Package, ArrowRightLeft, Tag,
  ShieldAlert, MessageSquareWarning, Plus, Eye,
  ChevronDown, RotateCcw, FileText, Sparkles,
} from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';

interface PromptStudioProps {
  config: Record<string, any>;
  onChange: (updates: Record<string, any>) => void;
}

interface PromptSection {
  key: string;
  label: string;
  icon: any;
  description: string;
  examples: string;
  autoGenerated?: boolean;
}

const SECTIONS: PromptSection[] = [
  {
    key: 'identity',
    label: 'Identidade e Personalidade',
    icon: User,
    description: 'Quem e o agente, tom de voz, regras gerais de comportamento.',
    examples: 'Ex: "Voce e a Ana, assistente da Eletropiso. Tom profissional e simpatico."',
  },
  {
    key: 'business_context',
    label: 'Contexto da Empresa',
    icon: ShoppingCart,
    description: 'Informacoes comerciais da empresa. Auto-gerado dos campos de Setup.',
    examples: 'Horario, endereco, formas de pagamento, entrega.',
    autoGenerated: true,
  },
  {
    key: 'sdr_flow',
    label: 'Fluxo SDR (Qualificacao)',
    icon: Sparkles,
    description: 'Como o agente qualifica o lead antes de buscar produtos no catalogo.',
    examples: 'Lead: "tem tinta?" → pergunte marca. Lead: "Coral" → busca imediata.',
  },
  {
    key: 'product_rules',
    label: 'Regras de Produtos e Midia',
    icon: Package,
    description: 'Quando buscar produtos, enviar foto vs carousel, quantidade de resultados.',
    examples: '1 produto = foto. 2+ = carousel. 0 = qualificacao → handoff.',
  },
  {
    key: 'handoff_rules',
    label: 'Regras de Transbordo',
    icon: ArrowRightLeft,
    description: 'Quando e como transferir para atendimento humano.',
    examples: 'Lead confirma compra → handoff. Emprego → RH. Financeiro → Financeiro.',
  },
  {
    key: 'tags_labels',
    label: 'Tags e Labels',
    icon: Tag,
    description: 'Classificacao de motivo, interesse, produto. Formato chave:valor.',
    examples: 'motivo:compra, interesse:tinta, produto:coral_premium_18l.',
  },
  {
    key: 'absolute_rules',
    label: 'Regras Absolutas',
    icon: ShieldAlert,
    description: 'Proibicoes criticas que nunca podem ser violadas. Validadas pelo Validator Agent.',
    examples: 'NUNCA inventar preco. NUNCA dizer "nao temos". Max 1 pergunta por msg.',
  },
  {
    key: 'objections',
    label: 'Deteccao de Objecoes',
    icon: MessageSquareWarning,
    description: 'Como lidar com objecoes do lead: preco, prazo, indecisao.',
    examples: '"ta caro" → empatia + beneficio. "vou pensar" → urgencia sutil.',
  },
  {
    key: 'additional',
    label: 'Instrucoes Adicionais',
    icon: Plus,
    description: 'Regras especificas da sua empresa que nao se encaixam acima.',
    examples: 'Campo livre para instrucoes personalizadas.',
  },
];

function estimateTokens(text: string): number {
  if (!text) return 0;
  // Rough estimate: 1 token ≈ 4 chars for Portuguese
  return Math.ceil(text.length / 4);
}

export function PromptStudio({ config, onChange }: PromptStudioProps) {
  const [defaults, setDefaults] = useState<Record<string, string>>({});
  const [expanded, setExpanded] = useState<Set<string>>(new Set(['identity', 'sdr_flow']));
  const [showPreview, setShowPreview] = useState(false);

  const sections = config.prompt_sections || {};

  // Load defaults from system_settings
  useEffect(() => {
    supabase
      .from('system_settings')
      .select('value')
      .eq('key', 'default_prompt_sections')
      .maybeSingle()
      .then(({ data }) => {
        if (data?.value && typeof data.value === 'object') {
          setDefaults(data.value as Record<string, string>);
        }
      });
  }, []);

  // Build business context from business_info (auto-generated, read-only)
  const businessContext = useMemo(() => {
    const bi = config.business_info || {};
    const parts: string[] = [];
    if (bi.hours) parts.push(`Horario: ${bi.hours}`);
    if (bi.address) parts.push(`Endereco: ${bi.address}`);
    if (bi.phone) parts.push(`Telefone: ${bi.phone}`);
    if (bi.payment_methods) parts.push(`Pagamento: ${bi.payment_methods}`);
    if (bi.delivery_info) parts.push(`Entrega: ${bi.delivery_info}`);
    if (bi.extra) parts.push(`Outros: ${bi.extra}`);
    return parts.length > 0
      ? `Informacoes da Empresa:\n${parts.join('\n')}`
      : 'Nenhuma informacao da empresa cadastrada. Preencha na aba Setup → Informacoes da Empresa.';
  }, [config.business_info]);

  const getSectionText = (key: string): string => {
    if (key === 'business_context') return businessContext;
    return sections[key] || defaults[key] || '';
  };

  const isCustomized = (key: string): boolean => {
    return !!(sections[key] && sections[key] !== defaults[key]);
  };

  const handleSectionChange = (key: string, value: string) => {
    const updated = { ...sections, [key]: value };
    onChange({ prompt_sections: updated });
  };

  const handleRestore = (key: string) => {
    const updated = { ...sections };
    delete updated[key];
    onChange({ prompt_sections: updated });
  };

  const toggleSection = (key: string) => {
    setExpanded(prev => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  // Calculate total tokens
  const totalTokens = useMemo(() => {
    return SECTIONS.reduce((sum, s) => sum + estimateTokens(getSectionText(s.key)), 0);
  }, [sections, defaults, businessContext]);

  const tokenPercent = Math.min(100, Math.round((totalTokens / 4096) * 100));

  // Build full preview
  const fullPrompt = useMemo(() => {
    return SECTIONS.map(s => {
      const text = getSectionText(s.key);
      return text ? `[${s.label.toUpperCase()}]\n${text}` : null;
    }).filter(Boolean).join('\n\n');
  }, [sections, defaults, businessContext]);

  return (
    <div className="space-y-4">
      {/* Header */}
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-start sm:items-center justify-between gap-3 flex-wrap">
            <div>
              <CardTitle className="text-base flex items-center gap-2">
                <FileText className="w-4 h-4 text-primary" />
                Prompt Studio
              </CardTitle>
              <CardDescription>
                Edite cada secao do prompt independentemente. O sistema monta o prompt final combinando tudo.
              </CardDescription>
            </div>
            <div className="flex items-center gap-3">
              <div className="hidden sm:block text-right">
                <div className="text-sm font-medium">{totalTokens} tokens</div>
                <div className="w-24 h-1.5 bg-muted rounded-full overflow-hidden">
                  <div
                    className={`h-full rounded-full transition-all ${tokenPercent > 80 ? 'bg-destructive' : tokenPercent > 60 ? 'bg-yellow-500' : 'bg-primary'}`}
                    style={{ width: `${tokenPercent}%` }}
                  />
                </div>
                <div className="text-[10px] text-muted-foreground">{tokenPercent}% do limite</div>
              </div>
              <Button variant="outline" size="sm" onClick={() => setShowPreview(true)}>
                <Eye className="w-4 h-4 mr-1" />
                Preview
              </Button>
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Sections */}
      {SECTIONS.map((section) => {
        const text = getSectionText(section.key);
        const tokens = estimateTokens(text);
        const customized = isCustomized(section.key);
        const Icon = section.icon;

        return (
          <Collapsible
            key={section.key}
            open={expanded.has(section.key)}
            onOpenChange={() => toggleSection(section.key)}
          >
            <Card className={customized ? 'border-primary/30' : ''}>
              <CollapsibleTrigger asChild>
                <CardHeader className="pb-2 cursor-pointer hover:bg-muted/30 transition-colors">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Icon className="w-4 h-4 text-primary" />
                      <CardTitle className="text-sm">{section.label}</CardTitle>
                      {customized && <Badge variant="default" className="text-[9px] px-1.5 py-0">Editado</Badge>}
                      {section.autoGenerated && <Badge variant="secondary" className="text-[9px] px-1.5 py-0">Auto</Badge>}
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-xs text-muted-foreground">{tokens} tok</span>
                      <ChevronDown className={`w-4 h-4 text-muted-foreground transition-transform ${expanded.has(section.key) ? 'rotate-180' : ''}`} />
                    </div>
                  </div>
                  <CardDescription className="text-xs">{section.description}</CardDescription>
                </CardHeader>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <CardContent className="pt-0 space-y-3">
                  <div className="text-xs text-muted-foreground bg-muted/50 rounded-md p-2">
                    {section.examples}
                  </div>

                  {section.autoGenerated ? (
                    <div className="bg-muted/30 rounded-md p-3 text-sm font-mono whitespace-pre-wrap">
                      {text || 'Preencha os campos em Setup → Informacoes da Empresa'}
                    </div>
                  ) : (
                    <>
                      <Textarea
                        value={sections[section.key] || defaults[section.key] || ''}
                        onChange={(e) => handleSectionChange(section.key, e.target.value)}
                        rows={Math.max(4, Math.min(12, (text || '').split('\n').length + 1))}
                        className="font-mono text-xs"
                        placeholder={defaults[section.key] || 'Escreva as instrucoes para esta secao...'}
                      />
                      <div className="flex items-center justify-between">
                        <span className="text-[10px] text-muted-foreground">
                          {customized ? 'Editado pelo admin' : 'Padrao do sistema'}
                        </span>
                        {customized && (
                          <Button variant="ghost" size="sm" className="h-6 text-xs" onClick={() => handleRestore(section.key)}>
                            <RotateCcw className="w-3 h-3 mr-1" />
                            Restaurar padrao
                          </Button>
                        )}
                      </div>
                    </>
                  )}
                </CardContent>
              </CollapsibleContent>
            </Card>
          </Collapsible>
        );
      })}

      {/* Preview Dialog */}
      <Dialog open={showPreview} onOpenChange={setShowPreview}>
        <DialogContent className="w-[95vw] sm:max-w-2xl max-h-[80vh]">
          <DialogHeader>
            <DialogTitle className="flex items-center justify-between">
              <span>Preview do Prompt Final</span>
              <Badge variant="outline">{totalTokens} tokens</Badge>
            </DialogTitle>
          </DialogHeader>
          <ScrollArea className="max-h-[60vh]">
            <pre className="text-xs font-mono whitespace-pre-wrap p-4 bg-muted/30 rounded-md">
              {fullPrompt}
            </pre>
          </ScrollArea>
        </DialogContent>
      </Dialog>
    </div>
  );
}
